config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "pages#home"
  get "about" => "pages#about"  
  get "library" => "pages#library"
  get "tails" => "pages#tails"
  get "breakout" => "pages#breakout"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def library
  end

  def tails
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<% if user_signed_in? %>


<footer class="footer">
      <div class="container">
          <p class="text-muted">
          <%= link_to "Library", root_path %>&nbsp&nbsp&nbsp
          <%= link_to "About", about_path %>&nbsp&nbsp&nbsp
          <%= link_to "Log out", destroy_user_session_path, method: :delete %>&nbsp&nbsp&nbsp
          </p>
      </div>  
</footer>

<%else %>   


<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Classified Spectacular</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>

      
    <%= yield %>

    <%= render 'layouts/header' %>

</body>
</html>

app/views/pages/about.html.erb
<% if user_signed_in? %>

<div class="container">
<div class="center">
<div class="about">

<%= image_tag("/images/signature.png", :alt => "Classified Spectacular",  class: "img-responsive") %>

<p>Classified Spectacular is an invitation-only film library.
<br/><br/>
Invitation requests may be made <a href="mailto:justindlamb@gmail.com?Subject=Classified%20Spectacular%20Invitation%20Request" target="_top">here</a>.
</p>

</div>
</div>
</div>

<%else %>		

<div class="container">
<div class="center">
	<%= link_to image_tag('/images/cslogo2.png', :alt => "Classified Spectacular",  class: "img-responsive"), root_path %>
	<br/>
	<%= link_to "I Have A Log In", new_user_session_path, class: "btn btn-success btn-lg" %>&nbsp&nbsp
	<%= mail_to "justindlamb@gmail.com", "I Need A Log In", subject: "Classified Spectacular Invite Request", class: "btn btn-danger btn-lg" %>    
</div> 
</div>
      
 <% end %>	

app/views/pages/breakout.html.erb
<% if user_signed_in? %>

<div class="container">
<div class="center">

<%= link_to image_tag('/images/breakoutpremiere.png', :alt => "Premieres 2.15.16", class: "img-responsive"), root_path %>
<br/>
<p>Things get complicated for a Free Agent.<br/>
Written and Directed by Justin Lamb<br/>
Featuring Dylan Donahue</p><br/>
<%= link_to "Return to Library", root_path, class: "btn btn-danger" %>


</div>
</div>

<%else %> 


<div class="container">

	<div class="getinthemiddle">
	<%= link_to image_tag('/images/cslogo2.png', :alt => "Classified Spectacular",  class: "img-responsive"), root_path %>
	<br/>
	<%= link_to "I Have A Log In", new_user_session_path, class: "btn btn-success btn-lg" %>&nbsp&nbsp
	<%= mail_to "justindlamb@gmail.com", "I Need A Log In", subject: "Classified Spectacular Invite Request", class: "btn btn-danger btn-lg" %>    
	</div> 

</div>
      
 <% end %>	

app/views/pages/home.html.erb
<% if user_signed_in? %>

<div class="container">
<div class="center">	

	<% flash.each do |name, msg| %>
	<%= content_tag(:div, msg, class: "alert alert-success") %>
	<% end %>

	<div class="librarymain">
	<%= link_to image_tag('/images/breakout.png',  :alt => "Breakout", class: "img-thumbnail"), breakout_path %>&nbsp
	<%= link_to image_tag('/images/tails.png',  :alt => "Tails",  class: "img-thumbnail"), tails_path %>
	</div>

</div>
</div>

<%else %>		

<div class="container">
<div class="center">	
	<%= link_to image_tag('/images/cslogo2.png', :alt => "Classified Spectacular",  class: "img-responsive"), root_path %>
	<br/>
	<%= link_to "I Have A Log In", new_user_session_path, class: "btn btn-success btn-lg" %>&nbsp&nbsp
	<%= mail_to "justindlamb@gmail.com", "I Need A Log In", subject: "Classified Spectacular Invite Request", class: "btn btn-danger btn-lg" %>    
	
</div> 
</div>
      
 <% end %>	

app/views/pages/library.html.erb
<% if user_signed_in? %>

<div class="container">
<div class="center">	
<div class="librarymain">

<%= link_to image_tag('/images/breakout.png',  :alt => "Breakout",  class: "img-thumbnail"), breakout_path %>
<%= link_to image_tag('/images/tails.png',  :alt => "Tails",  class: "img-thumbnail"), tails_path %>

</div>
</div>
</div>

<%else %>		

<div class="container">

	<div class="getinthemiddle">
	<%= link_to image_tag('/images/cslogo2.png', :alt => "Classified Spectacular",  class: "img-responsive"), root_path %>
	<br/>
	<%= link_to "I Have A Log In", new_user_session_path, class: "btn btn-success btn-lg" %>&nbsp&nbsp
	<%= mail_to "justindlamb@gmail.com", "I Need A Log In", subject: "Classified Spectacular Invite Request", class: "btn btn-danger btn-lg" %>    
	</div> 

</div>
      
 <% end %>	


app/views/pages/tails.html.erb
<% if user_signed_in? %>

<div class="container">
<div class="center">

<%= link_to image_tag('/images/tailspremiere.png', :alt => "Premieres 2.15.16",  class: "img-responsive"), root_path %>
<br/>
<p>Three strangers are unknowingly bound together by murder.<br/>
Written and Directed by Justin Lamb<br/>
Featuring Erin Bartley, Jonathan Bock, Evan Caminti, Tanner Dahlin, Matt Davidson, Sara Feinstein, Sean O'Reilly, Johnna Scrabis, Kris Weiner and Keisha Zoller.</p>
<br/>
<%= link_to "Return to Library", root_path, class: "btn btn-danger" %>

</div>
</div>

<%else %> 

<div class="container">

	<div class="getinthemiddle">
	<%= link_to image_tag('/images/cslogo2.png', :alt => "Classified Spectacular",  class: "img-responsive"), root_path %>
	<br/>
	<%= link_to "I Have A Log In", new_user_session_path, class: "btn btn-success btn-lg" %>&nbsp&nbsp
	<%= mail_to "justindlamb@gmail.com", "I Need A Log In", subject: "Classified Spectacular Invite Request", class: "btn btn-danger btn-lg" %>    
	</div> 

</div>
      
 <% end %>	